language: node_js
dist: trusty
sudo: required
node_js:
  - "node"
  - "8"
  - "7"
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - truffle test 
after_success:
  - npm run coverage
