language: node_js
dist: trusty
sudo: required
node_js:
  - "8"
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - npm run lint
script:
  - npm run test
after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls
